(function(g){var window=this;var Dua=function(a,b,c,d){var e=b.dc();g.S(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.Vb(c,d?d:"mqdefault.jpg");var k=b instanceof g.bQ?g.GV(b.lengthSeconds):null,l=!!f,f=l&&"RD"==g.DP(f).type,m=b instanceof g.bQ?b.Aa:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.T("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Hm(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.CQ&&(c.playlist_length=b.getLength());a.update(c)},A8=function(a,b){g.FV.call(this,{K:"div",
ea:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.g=a;this.N=!1},B8=function(a){g.KZ.call(this,a,{K:"div",
ea:["ytp-thumbnail-overlay","ytp-channel-overlay"],O:[{K:"div",W:"ytp-thumbnail-overlay-image",Z:{style:"{{background}}"}},{K:"div",W:"ytp-thumbnail-overlay-curtain"}]})},C8=function(a){var b={K:"div",
W:"ytp-upnext",Z:{"aria-label":"{{watch}}"},O:[{K:"div",W:"ytp-thumbnail-overlay-image",Z:{style:"{{background}}"}},{K:"div",W:"ytp-thumbnail-overlay-curtain"},{K:"span",W:"ytp-upnext-top",O:[{K:"span",W:"ytp-upnext-header",O:[g.T("YTP_PLAYLIST_UP_NEXT")]},{K:"span",W:"ytp-upnext-title",O:["{{title}}"]},{K:"span",W:"ytp-upnext-author",O:["{{author}}"]}]},{K:"a",W:"ytp-upnext-autoplay-icon",Z:{href:"{{url}}","aria-label":g.T("YTP_AUTOPLAY_NEXT")},O:[{K:"svg",Z:{height:"100%",version:"1.1",viewBox:"0 0 98 98",
width:"100%"},O:[{K:"circle",W:"ytp-svg-autoplay-circle",Z:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{K:"circle",W:"ytp-svg-autoplay-ring",Z:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{K:"polygon",W:"ytp-svg-autoplay-triangle",Z:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{K:"span",W:"ytp-upnext-bottom",O:[{K:"span",W:"ytp-upnext-cancel"},{K:"span",W:"ytp-upnext-paused",
O:[g.T("YTP_AUTOPLAY_PAUSED_3")]}]},{K:"span",W:"ytp-upnext-close"}]};g.W.call(this,b);this.B=null;var c=this.wa["ytp-upnext-cancel"],b=this.wa["ytp-upnext-close"];this.B=new g.W({K:"button",ea:["ytp-upnext-cancel-button","ytp-button"],Z:{tabindex:0,"aria-label":g.T("YTP_AUTOPLAY_CANCEL")},O:[g.T("YTP_CANCEL")]});g.N(this,this.B);this.B.T("click",this.Oy,this);this.B.Ia(c);c=new g.W({K:"button",ea:["ytp-upnext-close-button","ytp-button"],Z:{"aria-label":g.T("YTP_AUTOPLAY_CANCEL")}});g.N(this,c);c.T("click",
this.Oy,this);c.Ia(b);this.g=a;this.J=this.wa["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.ut(this.Vl,5E3,this);g.N(this,this.G);this.H=0;this.U(this.wa["ytp-upnext-autoplay-icon"],"click",this.cN);this.Ly();this.U(a,"autonavvisibility",this.Ly);this.U(a,"mdxnowautoplaying",this.qM);this.U(a,"mdxautoplaycanceled",this.rM);this.U(a,"mdxautoplayupnext",this.MA);3==this.g.Za()&&(a=(a=g.XU(g.SU(this.g)))?a.kG():null)&&this.MA(a)},Eua=function(a,b){a.C=b;
Dua(a,b,g.X(a.g),"hqdefault.jpg")},D8=function(a,b){a.A||(g.aG("a11y-announce",g.T("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.H=(0,g.mG)(),a.A=new g.ut((0,g.B)(a.gp,a,b),25),a.gp(b));
g.Pp(a.element,"ytp-upnext-autoplay-paused")},F8=function(a){E8(a);
a.H=(0,g.mG)();a.gp();g.R(a.element,"ytp-upnext-autoplay-paused")},E8=function(a){a.A&&(a.A.dispose(),a.A=null)},G8=function(a){A8.call(this,a,"subscribecard-endscreen");
var b=a.ha();this.A=new B8(a);g.N(this,this.A);g.pV(this.g,this.A.element,5);this.B=new g.W(["div","ytp-subscribe-card",["img","ytp-author-image",{src:b.profilePicture}],["div","ytp-subscribe-card-right",["div","ytp-author-name",b.author],["div","html5-subscribe-button-container"]]]);g.N(this,this.B);this.B.Ia(this.element);this.C=new g.w1(g.T("YTP_SUBSCRIBE"),null,g.T("YTP_UNSUBSCRIBE"),null,!0,!1,b.Rk,b.subscribed,"trailer-endscreen",null,null,a);g.N(this,this.C);this.C.Ia(this.B.wa["html5-subscribe-button-container"]);
this.oa()},H8=function(a){var b=g.X(a),b=b.A&&!b.D;
g.W.call(this,{K:"a",W:"ytp-videowall-still",Z:{href:"{{url}}",target:b?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},O:[{K:"div",W:"ytp-videowall-still-image",Z:{style:"{{background}}"}},{K:"span",W:"ytp-videowall-still-info",O:[{K:"span",W:"ytp-videowall-still-info-bg",O:[{K:"span",W:"ytp-videowall-still-info-content",Z:g.PE||g.We?{style:"will-change: opacity"}:void 0,O:[{K:"span",W:"ytp-videowall-still-info-title",O:["{{title}}"]},
{K:"span",W:"ytp-videowall-still-info-author",O:["{{author_and_views}}"]},{K:"span",W:"ytp-videowall-still-info-live",O:[g.T("YTP_LIVE")]},{K:"span",W:"ytp-videowall-still-info-duration",O:["{{duration}}"]}]}]}]},{K:"span",ea:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],O:[{K:"span",W:"ytp-videowall-still-listlabel-icon"},g.T("YTP_PLAYLIST"),{K:"span",W:"ytp-videowall-still-listlabel-length",O:[" (",{K:"span",O:["{{playlist_length}}"]},")"]}]},{K:"span",ea:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],O:[{K:"span",W:"ytp-videowall-still-listlabel-mix-icon"},g.T("YTP_MIX"),{K:"span",W:"ytp-videowall-still-listlabel-length",O:[" (50+)"]}]}]});this.B=b;this.g=a;this.A=null;this.T("click",this.C);this.T("keypress",this.D);g.X(a).da&&(a=a.app.ba,g.ib(a.A,this),b=String(a.G++),this.element.setAttribute("data-visual-id",b),g.Re(this,(0,g.B)(a.F,a,this)))},I8=function(a,b){A8.call(this,a,"videowall-endscreen");
this.ca=a;this.da=b;this.G=0;this.A=[];this.H=this.D=this.C=null;this.J=this.S=!1;this.F=new g.zL(this);g.N(this,this.F);this.L=new g.ut(g.ya(g.R,this.element,"ytp-show-tiles"),0);g.N(this,this.L);var c=new g.W({K:"button",ea:["ytp-button","ytp-endscreen-previous"],Z:{"aria-label":g.T("YTP_PREVIOUS")},O:[g.QD()]});g.N(this,c);c.Ia(this.element);c.T("click",this.sS,this);this.M=new g.VQ({K:"div",W:"ytp-endscreen-content"});g.N(this,this.M);this.M.Ia(this.element);c=new g.W({K:"button",ea:["ytp-button",
"ytp-endscreen-next"],Z:{"aria-label":g.T("YTP_NEXT")},O:[g.RD()]});g.N(this,c);c.Ia(this.element);c.T("click",this.rS,this);this.B=new C8(a);g.N(this,this.B);g.pV(this.g,this.B.element,5);this.oa()},J8=function(a){return g.qV(a.g)&&a.lp()&&!a.H},Fua=function(a){return(0,g.I)(a.Pf,function(a){return g.CZ(a)})},Gua=function(a,b,c){return 0==b&&a.C.length&&(b=c/I8.g,2<=c/I8.g&&2<=b&&g.X(a.g).experiments.g("video_wall_emphasize_first"))?2*I8.g:I8.g},K8=function(a){var b=a.kt();
b!=a.S&&(a.S=b,a.g.V("autonavvisibility"))},L8=function(a){g.AV.call(this,a);
g.MD({});this.o=null;this.isAvailable=!0;this.A=new g.zL(this);g.N(this,this.A);this.B=g.X(a);Hua(a)?this.o=new I8(this.g,this):this.B.Ta?this.o=new G8(this.g):this.o=new A8(this.g);g.N(this,this.o);g.pV(this.g,this.o.element,5);this.Vz();this.A.U(a,"videodatachange",this.Vz,this);this.A.U(a,"crn_endscreen",this.VR,this);this.A.U(a,"crx_endscreen",this.WR,this)},Hua=function(a){a=g.X(a);
return a.ac&&!a.Ta};g.C(A8,g.FV);A8.prototype.create=function(){this.N=!0};
A8.prototype.destroy=function(){this.N=!1};
A8.prototype.lp=function(){return!1};
A8.prototype.kt=function(){return!1};g.p(B8,g.KZ);B8.prototype.Jb=function(a){a?this.A.show():g.NV(this.A)};g.p(C8,g.W);g.h=C8.prototype;g.h.Vl=function(){this.D&&(this.G.stop(),this.Ba(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.Ly=function(){this.Jb(g.TU(this.g))};
g.h.SM=function(){window.focus();this.Vl()};
g.h.oa=function(){g.W.prototype.oa.call(this)};
g.h.gp=function(a){a=a||g.X(this.g).experiments.o("autoplay_time")||1E4;var b=Math.min((0,g.mG)()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.g.Za()?this.select(!0):this.A&&this.A.start()};
g.h.select=function(a){a=void 0===a?!1:a;var b=g.X(this.g);if(b.experiments.g("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.eV(this.g,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.C.dc(),this.Vl(),this.D=new window.Notification(g.T("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.Vb(b)}),this.F=this.U(this.D,"click",this.SM),this.G.start())}E8(this);
this.g.Gj(!1,a)};
g.h.cN=function(a){!g.Ee(this.B.element,g.zF(a))&&g.PV(a,this.g)&&this.select()};
g.h.Oy=function(){g.fV(this.g,"autonavcancel");g.VU(this.g,!0)};
g.h.qM=function(a){this.g.Za();this.show();D8(this,a)};
g.h.MA=function(a){this.g.Za();this.C&&this.C.dc().videoId==a.dc().videoId||Eua(this,a)};
g.h.rM=function(){this.g.Za();E8(this);this.oa()};
g.h.P=function(){E8(this);this.Vl();g.W.prototype.P.call(this)};g.C(G8,A8);G8.prototype.show=function(){G8.R.show.call(this);this.A.Jb(!0)};
G8.prototype.oa=function(){G8.R.oa.call(this);this.A.Jb(!1)};g.p(H8,g.W);H8.prototype.oj=function(){var a=this.A.dc().videoId,b=this.A.getPlaylistId();g.C2(this.g.app,a,this.A.Id,b,void 0,void 0)};
H8.prototype.C=function(a){g.tV(this.g,this);var b=(g.X(this.g).experiments.g("web_player_endscreen_new_tab")||!this.g.isFullscreen())&&this.B;g.PV(a,this.g,b,this.A.Id||void 0)&&this.oj()};
H8.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.EF(a)||(this.oj(),g.GF(a))}};g.C(I8,A8);I8.g=2;g.h=I8.prototype;g.h.create=function(){I8.R.create.call(this);var a=this.g.ha();a&&(this.C=Fua(a),this.D=a);this.ph();this.F.U(this.g,"appresize",this.ph);this.F.U(this.g,"videodatachange",this.tS);this.F.U(this.g,"autonavchange",this.FB);this.F.U(this.g,"autonavcancel",this.qS);this.F.U(this.element,"transitionend",this.iO)};
g.h.destroy=function(){g.BL(this.F);g.Te(this.A);this.A=[];this.C=null;I8.R.destroy.call(this);g.Pp(this.element,"ytp-show-tiles");this.L.stop()};
g.h.lp=function(){return 1!=this.D.autonavState};
g.h.show=function(){I8.R.show.call(this);g.Pp(this.element,"ytp-show-tiles");g.X(this.g).isMobile?g.vt(this.L):this.L.start();(this.J||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.VU(this.g,!1);var a=J8(this);g.qV(this.g)&&g.X(this.g).experiments.g("ui_logging")&&this.da.log({cancelButtonShow:a?"1":"0",state:this.lp()?"enabled":"disabled"});a?(K8(this),2==this.D.autonavState?g.X(this.g).experiments.g("fast_autonav_in_background")&&3==this.g.to()?this.B.select(!0):D8(this.B):3==this.D.autonavState&&
F8(this.B)):(g.VU(this.g,!0),K8(this))};
g.h.oa=function(){I8.R.oa.call(this);F8(this.B);K8(this)};
g.h.iO=function(a){g.zF(a)==this.element&&this.ph()};
g.h.ph=function(){if(this.C&&this.C.length){g.R(this.element,"ytp-endscreen-paginate");var a=g.vh(this.element),b=a.width/a.height,c=96/54,d=I8.g,e=I8.g,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(I8.g,2),n=Gua(this,0,k),q=Gua(this,1,k);var r=l*m+(Math.pow(n,2)-m);r+=Math.pow(q,2)-m;for(r-=m;0<r&&(d<f||e<k);){var v=d/I8.g;var x=e/I8.g;var A=d<=f-I8.g&&r>=x*m,E=e<=k-I8.g&&r>=v*m;if((v+1)/x*c/b>b/(v/(x+1)*c)&&E)r-=v*m,e+=I8.g;else if(A)r-=x*m,d+=I8.g;else if(E)r-=v*
m,e+=I8.g;else break}c=!1;f=I8.g+n;r>=3*m&&6>=l*m-r&&(e>=f||d>=f)&&q<=I8.g&&(c=!0);r=96*d;m=54*e;b=r/m<b?a.height/m:a.width/r;b=Math.min(b,2);r*=b;m*=b;r*=g.Qd(a.width/r||1,1,1.21);m*=g.Qd(a.height/m||1,1,1.21);r=Math.floor(Math.min(a.width,r));m=Math.floor(Math.min(a.height,m));a=this.M.element;g.uh(a,r,m);g.ch(a,{marginLeft:r/-2+"px",marginTop:m/-2+"px"});Eua(this.B,this.C[0]);g.S(this.element,"ytp-endscreen-takeover",J8(this));K8(this);b=r+4;r=m+4;m=0;f=!1;for(k=0;k<d;k++)for(v=0;v<e;v++)if(A=
q>I8.g&&1<=m&&!f?m+1:m,E=0,c&&k>=d-I8.g&&v>=e-I8.g?E=1:0==v%I8.g&&0==k%I8.g&&(v<n&&k<n?0==v&&0==k&&(E=n):q>I8.g&&v>=e-q&&k>=d-q?v==e-q&&k==d-q&&(f=!0,A=1,E=q):E=I8.g),A=g.Rd(A+this.G,l),0!=E){x=this.A[m];x||(x=new H8(this.g),this.A[m]=x,a.appendChild(x.element));var J=Math.floor(r*v/e),Z=Math.floor(b*k/d),Ta=Math.floor(r*(v+E)/e)-J-4,eb=Math.floor(b*(k+E)/d)-Z-4;g.jh(x.element,Z,J);g.uh(x.element,eb,Ta);g.ch(x.element,"transitionDelay",(v+k)/20+"s");g.S(x.element,"ytp-videowall-still-mini",1==E);
g.S(x.element,"ytp-videowall-still-large",2<E);A=this.C[A];x.A=A;Dua(x,A,g.X(x.g),g.Np(x.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");E=A.Id;A=x.g;g.X(A).da&&(A=A.app.ba,E=E&&E.itct,x=x.element.getAttribute("data-visual-id"),g.rV(A,"onLogServerVeCreated",{id:x,tracking_params:E}));m++}g.S(this.element,"ytp-endscreen-paginate",m<l);for(d=this.A.length-1;d>=m;d--)x=this.A[d],g.xe(x.element),g.Se(x);this.A.length=m}};
I8.A=2;I8.o=1.21;g.h=I8.prototype;g.h.tS=function(){var a=this.g.ha();this.D!=a&&(this.G=0,this.C=Fua(a),this.D=a,this.ph())};
g.h.rS=function(){this.G+=this.A.length;this.ph()};
g.h.sS=function(){this.G-=this.A.length;this.ph()};
g.h.rI=function(){return!!this.B.A};
g.h.FB=function(a){1==a?(this.J=!1,this.H=this.D.clientPlaybackNonce,E8(this.B),this.o&&this.ph()):(this.J=!0,this.o&&J8(this)&&(2==a?D8(this.B):3==a&&F8(this.B)))};
g.h.qS=function(a){if(a){for(a=0;a<this.A.length;a++)g.uV(this.ca,this.A[a],!0);this.FB(1)}else this.H=null,this.J=!1;this.ph()};
g.h.kt=function(){return this.o&&J8(this)};g.C(L8,g.AV);g.h=L8.prototype;g.h.AB=function(){var a=this.g.ha(),b=!Hua(this.g)||!(!a.Pf||!a.Pf.length),a=g.vQ(a,"ypc_module"),c=g.MZ(this.g.app);return(b||!1)&&!a&&!c};
g.h.zB=function(){return this.o.kt()};
g.h.pI=function(){return this.zB()?this.o.rI():!1};
g.h.P=function(){g.nV(this.g,"endscreen");L8.R.P.call(this)};
g.h.load=function(){L8.R.load.call(this);this.o.show();g.X(this.g).Ta&&.01>Math.random()&&this.log({trailerEndscreenShow:1})};
g.h.log=function(a){g.eV(this.g,"end",a)};
g.h.unload=function(){L8.R.unload.call(this);this.o.oa();this.o.destroy();this.isAvailable=!1};
g.h.VR=function(a){this.AB()&&(this.o.N||this.o.create(),"load"==a.getId()&&this.load())};
g.h.WR=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Vz=function(){g.nV(this.g,"endscreen");var a=Math.max(1E3*(this.g.ha().lengthSeconds-10),0),a=new g.LS(a,0x8000000000000,{id:"preload",namespace:"endscreen"}),b=new g.LS(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.kV(this.g,[a,b])};window._exportCheck==g.Ba&&g.u("ytmod.player.endscreen",L8,void 0);})(_yt_player);
